### ISSUE TITLE
Blockly doesn't show blocks to modify variables

### ISSUE THREAD

**Issue by OxygenL602** [Pen-Group/penPlus-shader-editor#13]
Blockly now doesn't show blocks to modify variables with scope varying
![image](https://github.com/user-attachments/assets/1e78c0e4-a1a3-46ec-9384-2f7663c593af)

**Comment by David-Orangemoon** [comment]
thanks. I'll get to fixing that.

**Comment by David-Orangemoon** [comment]
Fixed in https://github.com/Pen-Group/penPlus-shader-editor/commit/1b4e8ae70630283bba4f68e53e9b674eceadf12d
