### ISSUE TITLE
Cannot set properties of undefined

### ISSUE THREAD

**Issue by OxygenL602** [Pen-Group/penPlus-shader-editor#15]
Just started appearing at random.
![image](https://github.com/user-attachments/assets/8e6e6565-f5f8-4f7a-b9f8-3cca0240bed6)
Line that caused the error:
`buffer.numElements = 6;` (buffer being null)

**Comment by OxygenL602** [comment]
Also, when trying to compile a shader with version 300, it returns a error: `*** Error compiling shader: ERROR: unsupported shader version` even though the shader is completely fine.

**Comment by OxygenL602** [comment]
Browser = Chromium(TW Desktop App), TW Version = 1.12.3

**Comment by David-Orangemoon** [comment]
> Browser = Chromium(TW Desktop App), TW Version = 1.12.3

Turbowarp desktop does not support webgl 2.0 yet. So version 300 can't be used on desktop. Sorry

**Comment by David-Orangemoon** [comment]
Not related to the shader editor. More of a TW problem.
